<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="C02C61S0MD6T" name="com.TestNGTutorials.TestNGSoftAssert" tests="1" failures="1" timestamp="10 Feb 2021 02:51:30 GMT" time="0.009" errors="0">
  <testcase name="testExportData" time="0.009" classname="com.TestNGTutorials.TestNGSoftAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
serviceid wrong expected [12] but found [18], servicename wrong expected [ ] but found [Yahoo], servicename wrong expected [user2] but found [user1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
serviceid wrong expected [12] but found [18], servicename wrong expected [ ] but found [Yahoo], servicename wrong expected [user2] but found [user1]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at com.TestNGTutorials.TestNGSoftAssert.testExportData(TestNGSoftAssert.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testExportData -->
</testsuite> <!-- com.TestNGTutorials.TestNGSoftAssert -->
